name: "Hello World Workflow"

# Controls when the actions will run. Triggers the workflow on push to master or production branch

on:
  push:
    branches:
      - main
      - production

jobs:
  hello_world: # Corrected: hellow_world -> hello_world
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "Hello World" # Corrected: Hellow World -> Hello World